import pandas as pd

import matplotlib.pyplot as plt


# 1. LOAD THE PREPARED DATASET

df = pd.read_csv("data/retail_sales_prepared.csv")

# Convert the Date column from string format to datetime format
df["Date"] = pd.to_datetime(df["Date"])


print(df.shape)

print(df.info())



# 2. BASIC SALES STATISTICS

print("\nSales Statistics:")

# Generate statistical information about Weekly_Sales
print(df["Weekly_Sales"].describe())


# 3. TOTAL SALES OVER TIME
sales_over_time = (
    df.groupby("Date")["Weekly_Sales"]
    .sum()
    .reset_index()
)

# Display the first few rows
print(sales_over_time.head())


# Create a figure for the time-series plot
plt.figure(figsize=(14, 6))

# Plot total sales against date
plt.plot(
    sales_over_time["Date"],
    sales_over_time["Weekly_Sales"]
)

# Add title and axis labels
plt.title("Total Weekly Retail Sales")
plt.xlabel("Date")
plt.ylabel("Weekly Sales")

plt.xticks(rotation=45)

plt.tight_layout()

plt.show()


# 4. SALES BY STORE

# Calculate total sales generated by each store
store_sales = (
    df.groupby("Store")["Weekly_Sales"]
    .sum()
    .sort_values(ascending=False)
)

print(store_sales.head(10))

# Create a bar chart
plt.figure(figsize=(12, 6))

# Plot total sales for each store
store_sales.plot(kind="bar")

plt.title("Total Sales by Store")
plt.xlabel("Store")
plt.ylabel("Total Sales")

plt.tight_layout()

plt.show()


# 5. HOLIDAY VS NON-HOLIDAY SALES
holiday_sales = (
    df.groupby("IsHoliday")["Weekly_Sales"]
    .mean()
)

# Display the average sales
print(holiday_sales)


# Create a bar chart
holiday_sales.plot(
    kind="bar",
    figsize=(7, 5)
)

# Add title and labels
plt.title("Average Sales: Holiday vs Non-Holiday")
plt.xlabel("Holiday")
plt.ylabel("Average Weekly Sales")

plt.tight_layout()

plt.show()


# 6. MONTHLY SALES / SEASONALITY

df["Month"] = df["Date"].dt.month

monthly_sales = (
    df.groupby("Month")["Weekly_Sales"]
    .mean()
)

print(monthly_sales)


# Create a line plot
plt.figure(figsize=(10, 5))

# Plot average sales by month
monthly_sales.plot(marker="o")

plt.title("Average Sales by Month")
plt.xlabel("Month")
plt.ylabel("Average Weekly Sales")

plt.xticks(range(1, 13))

plt.tight_layout()

plt.show()


# 7. CHECK FOR MISSING VALUES
print("\nMissing values:")

print(df.isnull().sum())